name: bloomee_dart_api
description: A new shelf server.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.0
  youtube_explode_dart: ^2.2.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
